server:
  port: 9090
cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    credentials:
    end-point:
      uri:
    stack:
      auto: false
application:
  bucket:
    name: javalearns3bucketRitesh
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB